### PR TITLE
Add GetVehicleSpeed() and SetVehicleSpeed() implementations.

### PR DESCRIPTION
**Pull request by shierru**
This **PR** is essentially my question to the very essence of stdlib.

Let's start with the fact that if we take the direct meaning of this repository, then it is the same as in other programming languages. The essence is the same. And I thought, for some reason, using the “powers” of the **Pawn language** to implement some functions related to vehicles, namely `GetVehicleSpeed()` and `SetVehicleSpeed()`, these functions, I think, are often used in gamemodes so that they are in **omp-stdlib**. And it’s strange why they are not in **open.mp** itself (that would be logical).

As for the name of the section in **omp-stdlib** (I'm talking about "_Implementations_"). I thought for a long time what to call it, nothing else came to mind.

The direct point of this PR is that the `GetVehicleSpeed()` and `SetVehicleSpeed()` functions are already available out of the box, because these functions, as I said above, are quite common in gamemodes.

### CODE REVIEW

**Comment by shierru** [comment]
P.S. I've been looking for **FIGlet font** for quite a long time and finally found the one)

**Comment by shierru** [comment]
Oh yes. It just occurred to me that this might break backwards compatibility if these functions are already available in the developers gamemodes.

**Comment by Y-Less** [comment]
I understand the philosophical question of what a standard library really should be, but if this function really is so fundamentally useful, then it should be in the server itself so that it is accessible from C++ as well as from Pawn.

In terms of actual code, this:

```pawn
velocityPowerX = floatpower(velocityX, 2.0);
```

Is far better as something like:

```pawn
velocityX = velocityX * velocityX;
```

Fewer declared variables and using `floatpower` to square is very inefficient compared to just multiplying.

**Comment by shierru** [comment]
Thanks for the clarification, the PR is closed.

**Comment by Y-Less** [comment]
Most vehicle functions also return `true`/`false` when the vehicle does/doesn't exist, so you very rarely need an explicit `IsValidVehicle` when immediately followed by other functions.

I don't think `0.0` is the best failure return value, because it doesn't distinguish between stopped and non-existent.

When going backwards this code currently only returns a positive speed value.

The speed setting is inaccurate on a slope (you'll need to use the quat rotation).

In fact those points also raise some questions about the essence of vehicle "speed".  If it is falling is that it's "speed"?  It wouldn't be shown in the speedometer.  I don't know.

**Pull request closed without merging**
