### PR TITLE
Mostly supplemental documentation

### PR DESCRIPTION
**Pull request by shierru**

### CODE REVIEW

**Comment by shierru** [comment]
I am planning to write internal documentation for other includes where it is partially missing some functions (I pre-palogue that mostly functions that were added from YSF).

I would like to understand if this makes sense? 
Because maybe I'm simply writing the documentation wrong, I don't have a lot of experience.

Initially I decided to do this when I came across the problem that the **UsePlayerGangZoneCheck** function doesn't have the right set of parameters, namely the very first parameter **_playerid_** is missing (P.S. I fixed it in the #22).

**Comment by shierru** [comment]
I also think that in **PlayerPlaySound** should be parameters `Float:x, Float:y, Float:z` by default to make 0.0, so that the sound played not in 3D space. 

I have not changed this in this pull request (for now). I'm not quite sure if this would be correct or not?

**Review by AmyrAhmady — APPROVED** [review]

**Comment by shierru** [comment]
```pawn
native bool:GangZoneGetPos(zoneid, &Float:minX, &Float:minY = 0.0, &Float:maxX = 0.0, &Float:maxY = 0.0);
```

For some reason (unclear to me) only `minY, maxX, maxY` are optional parameters here, and `minX` is mandatory.

Is this a typo? Or does it carry some meaning?

**Comment by shierru** [comment]
P.S. I made the position parameters in the **PlayerPlaySound** function optional (issue #18).

**Comment by Y-Less** [comment]
Yes I'm not sure why those parameters are optional.  It does seem like a mistake.

**Pull request merged**
